### PR TITLE
Implement date token for author and committer

### PR DESCRIPTION
**Pull request by aBARICHELLO**
Hello there, i've implemented the date token as an alternative to `time.ago` since the date estimation is sometimes rounded and not exactly precise.

Let me know if this PR needs any extra changes.

### CODE REVIEW

**Comment by aBARICHELLO** [comment]
@Sertion

**Comment by Sertion** [comment]
Thank you for the pull request. Here is some feedback:
* Is there a reason to use `toDateString` over the iso variant? The iso variant will never require any localisation, follows a standardized format, and is still equally accurate.
* The current implementation includes and extra trailing whitespace at the end of the token.

// S

**Comment by aBARICHELLO** [comment]
@Sertion Done

**Comment by Sertion** [comment]
Thank you. That was quick!

I don't know when I can get the next version out. There are some blockers for me right now but this will be part of the next release.

**Comment by aBARICHELLO** [comment]
No problem. Thanks!

**Pull request merged**
